### ISSUE TITLE
Manage players doesn't show in HA iframe

### ISSUE THREAD

**Issue by Tirzite** [pssc/ha-addon-lms#13]
Hello, 

Material skin works fine with yaml option, but the manage players stay empty in HA iframe.
Manage players page works fine in a dedicated tab
in iframe :
![image](https://user-images.githubusercontent.com/28784781/173662772-e7affe89-5ec5-45bc-b8f3-9dee026f4979.png)
in dedicated tab : 
![image](https://user-images.githubusercontent.com/28784781/173662859-b976e7fd-bcae-4d4a-8f7d-d9491d2ed7da.png)

**Comment by pssc** [comment]
I see the same issue

**Comment by Pirionfr** [comment]
seems to be related to double // after html 
ex : https://.../hassio_ingress/...//html/font/font.css?r=49

**Comment by pssc** [comment]
Having trouble pinning this down in the rewrites for ingress
