### ISSUE TITLE
Problems with "help"

### ISSUE THREAD

**Issue by ovizii** [pssc/ha-addon-lms#14]
accessing help

![image](https://user-images.githubusercontent.com/837902/173781053-c2f7c664-3d0f-4637-95b3-b954df8eb1d0.png)

clicking any of these links:

![image](https://user-images.githubusercontent.com/837902/173781300-7f6dc8d8-5e2a-47d7-9335-99cfb30d96fa.png)

![image](https://user-images.githubusercontent.com/837902/173781403-1fb14aa7-3469-463e-b4c9-ed3f2c7b90e6.png)

**Comment by ovizii** [comment]
possibly related as I found this shortly afterwards in the logs:

```
2022/06/15 09:59:35 [error] 732#732: *524 upstream prematurely closed connection while reading response header from upstream, client: 172.30.32.2, server: fc57b866-lms, request: "POST /jsonrpc.js HTTP/1.1", upstream: "http://127.0.0.1:9000/jsonrpc.js", host: "myHAdomain.tld", referrer: "https://myHAdomain.tld/api/hassio_ingress/eRnjbB_-2ywb3W2RDq7BgNmxz_eY1tF0bdVBbYlHou8/"
parse error: Expected string key before ':' at line 1, column 4
```

**Comment by pssc** [comment]
looks like a likely ingress proxy issue will try and replicate

**Comment by pssc** [comment]
i have replicated the bug.
