### ISSUE TITLE
Seeing ClientConnectorError in lms logs

### ISSUE THREAD

**Issue by ovizii** [pssc/ha-addon-lms#15]
Seeing this error in the logs, not sure about its importance. I also installed your squeezelite add-on on this HA instance - might be related. its config is:

```
name: hasqueezy
server: 10.10.10.87
```

10.10.10.87 is the IP of HA/lms/squeezelite

```
[services.d] starting services
Start Logitech Media Server...
[services.d] done.
[09:36:47] INFO: Waiting for lms before starting NGinx...
[09:36:48] INFO: Starting NGinx...
error: ClientConnectorError: Cannot connect to host homeassistant.local:8123 ssl:default [No address associated with hostname]
Run with -x to see full exception information
[09:36:56] INFO: Event lms.service
{"message": "Event lms.service fired."}
```

**Comment by pssc** [comment]
Yes I have seen this also in my setup but I don't think it happens all the time, this is trying to fire an event into HA to say we have lms service now for triggers/automations

**Comment by pssc** [comment]
This is the hass-cli health check breaking
