### ISSUE TITLE
Allow Menu access for non admin users

### ISSUE THREAD

**Issue by amaduain** [pssc/ha-addon-lms#17]
Hi, it would be great if the addon can be seen by non admin users on the side menu.
I've been looking and it seems it is related with the addon option **panel_admin**
The info is here: [https://developers.home-assistant.io/docs/add-ons/configuration/](https://developers.home-assistant.io/docs/add-ons/configuration/)

Don't know if there are other limitations about this.

**Comment by pssc** [comment]
this should be implemented in the next release

**Comment by amaduain** [comment]
Hi Phill,
thanks for the heads up, it is a great addon, I'm using it with some moode raspberries and it is great to have it on the home assistant.
