### ISSUE TITLE
Some tmpfs issues..

### ISSUE THREAD

**Issue by sdvd111-bit** [pssc/ha-addon-lms#2]
Hi, 
I found your project by searching.  I use your add-on to TTS to homepod.  It worked well.
But it cannot start someday.  I found the following error in homeassistant log,
------
21-03-06 03:31:31 ERROR (SyncWorker_4) [supervisor.docker] Can't start addon_7222e6e9_lms: 500 Server Error for http+docker://localhost/v1.40/containers/5e6af787ebe7978f3e7850155bf817779b30f9c792c1e88c7d2801668f2ff60e/start: Internal Server Error ("OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "tmpfs" to rootfs at "/tmp" caused: mkdir /mnt/data/docker/overlay2/965c96293648ccec3809d30e5775101b2dced4cc5e7c943ce7836141d6929525/merged/tmp: file exists: unknown")_
-----
And I also find a warning in a warning in log of supervisor when I tried to upgrade homeassistant to 2020.3.2
--------
21-03-06 01:27:46 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'tmpfs' use a deprecated format, new it's only a boolean. Please report this to the maintainer of Logitech Media Server
--------

Please take a look when convenient.

**Comment by pssc** [comment]
Hi @sdvd111-bit  just testing a new build now,

**Comment by pssc** [comment]
This should be all fixed for a while now
