### ISSUE TITLE
LMS still shows up in server list after removal of the add on.

### ISSUE THREAD

**Issue by dirk77** [pssc/ha-addon-lms#20]
I tried the addon on my home assistant x86/64 server but could not get it to work with my USB drive, so I used the deinstallation button and removed the addon from my server. Unfortunately the removed server still shows in the server listing of my devices and my picoreplayer Raspberry pi still tries to connect to it.

**Comment by pssc** [comment]
@dirk77 hi yes you will need to unconfigure the players try going to your other server and pulling them across, they will remember the last connected sever regardless of its availability 

Using a usb stick is supported happy to work through why it's not working for you?

**Comment by DirkKer** [comment]
It's not the players, even a freshly installed squeezelite-X still "sees" the server that was uninstalled before.

About the USB drive... Looks like I'm simply too stupid to get it to work.

**Comment by pssc** [comment]
@DirkKer  could still be some saved config most players cache the discovered servers and or the current server,  unless it still running someware,  best check with ```docker ps```.  I have a good understanding of ths as I have looked at it for the squeezy cli tool and squeezeplay.  I have a few squeezelite-X instances here none are showing servers that are off, that were not configured as the server.

The addin doesn't touch the lms code bar a little bit of setup to avoid the setup wizard and uses the host networking to avoid more complex issues.

So could be I need to provide better instructions that assume less knowledge @DirkKer I have 25+ years experience as a Unix/linux sysadmin so what's obvious to me may not be to others...

**Comment by pssc** [comment]
Closing unless more information can be provided as I cant replaicte this issue
