### ISSUE TITLE
Permission denied at /usr/share/squeezeboxserver/CPAN

### ISSUE THREAD

**Issue by juhanjuku** [pssc/ha-addon-lms#28]
Since last December I can't use lms anymore. I'm getting 502: Bad Gateway when try to open web gui.
From logs I see that permissions are denied. I have made several times uninstall and new install but still same.
From forum posts I see other users having same problem, suggesting opening issue here.
https://community.home-assistant.io/t/home-assistant-community-addons-logitech-media-server-lms-squeezelite/338137/129?u=ratsepa
I'm running latest HA on Pi4.
[log.txt](https://github.com/pssc/ha-addon-lms/files/10527392/log.txt)

**Comment by pssc** [comment]
@juhanjuku Please toggle the set_permissions option to see if that fixes the issue.

**Comment by juhanjuku** [comment]
Unfortunately result is still same :(
[log.txt](https://github.com/pssc/ha-addon-lms/files/10533396/log.txt)

**Comment by pssc** [comment]
in the web terminal try ```chown  -hR 1000:1000 /config/lms```

**Comment by juhanjuku** [comment]
Excuse my low competence - where I find this web terminal?
My HA runs on Pi4

**Comment by juhanjuku** [comment]
Thank you, some restarts were needed, but now I see lms again :)
