### ISSUE TITLE
Privacy of HA users in LMS forum

### ISSUE THREAD

**Issue by JJFourie** [pssc/ha-addon-lms#29]
This may not be directly related to HA itself, but as the Logitech forum is referenced in the HA add-on to me there is some relation here to make it worth mentioning.

**Problem:** 
In the forum that is referred to in the HA add-on, the only option is to accept the privacy policy. It is not possible to reject use of private data. For a privacy-orientated application like HA this is unacceptable. 

In the caption of the add-on:
"_**Home Assistant Community Add-on: lms (Logitech Media Server)**_
_A complete and easy way to run the [Logitech Media Server](https://forums.slimdevices.com/)._"

![image](https://user-images.githubusercontent.com/49686555/215335080-cc938c0f-05c0-4dbf-b4e0-744ba77f0906.png)

**Comment by pssc** [comment]
I don't have any control or influence over the form and it is the place used by the LMS community.
