### ISSUE TITLE
Expose 'local player' to home assistant audio

### ISSUE THREAD

**Issue by funkybassmandan** [pssc/ha-addon-lms#3]
Hi.
This is my first post on Github, so apologies if I make a faux-pa!
Love this addon, I have been able to combine my nas and home assistant server into one! 
One small functionality that I am missing is the ability to play audio from the 'local player' in lms.
Is there a relatively easy fix to expose this to the home assistant audio? 
Regards.
Dan.

**Comment by pssc** [comment]
Looks like audio is not enabled in the config i will push that out in 0.45 and see if that does it.

**Comment by pssc** [comment]
@funkybassmandan, I am building v0.0.45 now, would you be up for testing this would mean some manual CLI action in home assistant and uninstalling the repo version?  I will have installed on my test setups here first, just to find any clangers.

**Comment by funkybassmandan** [comment]
Thanks for your reply. Of course I would be happy to try it, the system is not fully live yet, so breaking it wouldn't matter... Not that it will of course!😉

**Comment by pssc** [comment]
@funkybassmandan which arch are you using?

**Comment by funkybassmandan** [comment]
@pssc I'm running on a raspberry pi4 4GB, booting from ssd.

**Comment by pssc** [comment]
@funkybassmandan Are you 32bit of 64?

**Comment by pssc** [comment]
So I have now on my setup after a bit of poking  squeezelite connected to the HA pulse audio, will probably need to rebuild the image again due to extra packages and permissions that need to be set,  It takes ~1.5 days to produce the images for all arches, I also note the LocalPlayer plugin doesn't support aarch64 at all, unless you can run 32it arm binaries on that as well?

**Comment by funkybassmandan** [comment]
I'm running 64 bit, but happy to flash 32bit for the purposes of testing!
I appreciate the time you're putting to this. 😊

**Comment by pssc** [comment]
@funkybassmandan ok there seem to be issues with getting a working Squeezelite.  I ended compiling on up my own to get any sound out! so o this end have a look at https://github.com/pssc/ha-addon-squeezelite/ its a bit rough round the edges see if it meet your needs this should also work in aarch64 though this is currently untested.

**Comment by pssc** [comment]
I can confirm playback on Hassos aarch54 via pulse audio and direct HW
