### ISSUE TITLE
how to mount my USB flash drive?

### ISSUE THREAD

**Issue by tung256** [pssc/ha-addon-lms#31]
how to load MP3 files from my usb flash drive?
do i put anything in here?
![image](https://user-images.githubusercontent.com/37672036/224484224-de4fddec-1316-458d-b7d7-bd917ac864b6.png)

my HA OS on thin client can see the USB flash drive stick as seen here
![image](https://user-images.githubusercontent.com/37672036/224484192-e661cb00-0495-4250-8abb-0f97791aa26b.png)

as of now,  LMS does not see my mp3 folder on the usb stick:
![image](https://user-images.githubusercontent.com/37672036/224484321-06ab3a1c-8562-45bd-b3b2-a294c5fab62b.png)

**Comment by pssc** [comment]
Answered in forum not a bug

**Comment by tung256** [comment]
which forum?
i asked the same in the HA community but no response as seen here:  https://community.home-assistant.io/t/home-assistant-community-addons-logitech-media-server-lms-squeezelite/338137/152?u=tung256
i tried youtube also but no one seems to have this add on as well
