### ISSUE TITLE
Need some help getting started

### ISSUE THREAD

**Issue by ovizii** [pssc/ha-addon-lms#34]
After a few unsuccessful tries (see my older posts) I'd like to start over with this add-on. 
What would I need to do to make sure not old data/configs are left over?

What would the minimal config be if all I want is to let this add-on access my music from the host folder: /media/nas-music ? This folder is a samba mount (mount script gets executed upon HA startup). No fancy linking and stuff, just let this add-on access that host folder.

**Comment by pssc** [comment]
make sure /config/lms is removed manually , add your samba mount like to the mount option in the addon after testing in the Advanced web terminal you may need to toggle protection mode.
