### ISSUE TITLE
ui on Home Assistant screws up

### ISSUE THREAD

**Issue by sirhideo** [pssc/ha-addon-lms#38]
After changing the web interface the ui in home assistant screws up.  Once I changed web interface back to default it doesn't help either, then I try to clear all browser cache and use browser to visit http://my_ha:9000.  But if I click the side bar lms inside home assistant, the ui looks like the attached.   I can only use browser and visit the ip address port 9000 to get the ui right.  Clicking lms on home assistant side bar, no matter which browser i used to open HA, the lms ui always screws up. Removing the addon and reinstall it back didn't help either.
![lms-addon](https://user-images.githubusercontent.com/26427786/233227629-d5e8a826-c38d-46fa-8f62-2f7371ebcb7f.jpg)

**Comment by pssc** [comment]
High this do to caching restore to working config choose the right addon option for the lms skin close down the addon then clear down all the caches and restart browser.
