### ISSUE TITLE
Permission denied after update home assistant

### ISSUE THREAD

**Issue by Freez** [pssc/ha-addon-lms#45]
LMS doesn't start after upgrading Home Assistant & Home Assisant OS

Home Assistant 2023.6.3
Supervisor 2023.06.2
Operating System 10.3

`Start Logitech Media Server...
[23-06-28 12:35:13.6953] main::init (377) Starting Logitech Media Server (v8.3.0, 1667251155, Fri 04 Nov 2022 09:16:39 AM CET) perl 5.032001 - aarch64-linux-gnu-thread-multi
[23-06-28 12:35:13.7046] Slim::Utils::PluginManager::init (74) Failed to load plugin downloader: Can't locate Slim/Utils/PluginDownloader.pm:   /config/lms/cache/InstalledPlugins/Slim/Utils/PluginDownloader.pm: Permission denied at /usr/share/perl5/Slim/Utils/PluginManager.pm line 69.
[23-06-28 12:35:13.7542] main::init (507) Warning: Can't locate Slim/Networking/SqueezeNetwork.pm:   /config/lms/cache/InstalledPlugins/Slim/Networking/SqueezeNetwork.pm: Permission denied at /usr/sbin/squeezeboxserver line 507.`

**Comment by pssc** [comment]
@Freez please set the set_permissions option as it looks like the upgrade has knobbled the file ownership

**Comment by Freez** [comment]
@pssc unfortunately that doesn't matter

**Comment by Freez** [comment]
@pssc there is nothing in `/config/lms/cache/InstalledPlugins`

**Comment by pssc** [comment]
please supply the output of ```ls -la /config/lms/ /config/lms/cache```

**Comment by Freez** [comment]
`ls -la /config/lms /config/lms/cache 
/config/lms:
total 28
drwxr-xr-x    7 root     root          4096 Jan  6 14:11 .
drwxr-xr-x   13 root     root          4096 Jun 28 14:18 ..
drwx------    2 hassio   root          4096 Jun 15 13:36 addon
drwx------    8 hassio   root          4096 Jun 15 13:37 cache
drwx------    2 hassio   root          4096 Jun 28 09:17 logs
drwx------    2 hassio   root          4096 Jun 15 13:36 plugins
drwx------    3 hassio   root          4096 Jun 28 15:08 prefs

/config/lms/cache:
total 8292
drwx------    8 hassio   root          4096 Jun 15 13:37 .
drwxr-xr-x    7 root     root          4096 Jan  6 14:11 ..
drwx------    2 root     root          4096 Jun 15 13:37 DownloadedPlugins
drwx------    2 root     root          4096 Jun 15 13:37 InstalledPlugins
-rw-r--r--    1 root     root       1576960 Jun 15 13:37 artwork.db
drwx------    2 root     root          4096 Jun 15 13:36 audioUploads
-rw-r--r--    1 root     root        167936 Jun 15 13:37 cache.db
-rw-r--r--    1 root     root        951752 Jun 15 13:36 cache.db-wal
-rw-r--r--    1 root     root          1070 Jun 15 13:36 cookies.dat
-rw-r--r--    1 root     root           226 Jun 15 13:37 extrastrings.json
-rw-r--r--    1 root     root         16384 Jun 15 13:36 imgproxy.db
-rw-r--r--    1 root     root             0 Jun 15 13:36 imgproxy.db-wal
-rw-r--r--    1 root     root           731 Jun 15 13:37 infobrowser.opml
-rw-r--r--    1 root     root           165 Jun 15 13:37 infobrowser.opml.backup
-rw-r--r--    1 root     root       3944448 Jun 15 13:37 library.db
-rw-r--r--    1 root     root             0 Jun 15 13:37 library.db-wal
-rw-r--r--    1 root     root        757760 Jun 15 13:37 persist.db
-rw-r--r--    1 root     root        828152 Jun 15 13:37 persist.db-wal
-rw-r--r--    1 root     root         23370 Jun 15 13:37 plugin-data.yaml
-rw-r--r--    1 root     root        165266 Jun 15 13:36 stringcache.aarch64-linux.bin
drwx------    3 root     root          4096 Jun 15 13:37 templates
drwx------    2 hassio   root          4096 Jun 15 13:37 tmp
drwx------    2 root     root          4096 Jun 15 13:36 updates`

**Comment by pssc** [comment]
https://github.com/pssc/ha-addon-lms/commit/b4f14139f2a17258a10295aa436301730f1fc5ae

**Comment by Freez** [comment]
> try `chown -Rh 1000 /config/lms` in the terminal addon and restarting the addon

Works! Thank you!

**Comment by pssc** [comment]
This is the same as #47 really
