### ISSUE TITLE
Plugin v0.0.55 incompatible with crucial plugins. Possible to downgrad to previous version?

### ISSUE THREAD

**Issue by kylepyke** [pssc/ha-addon-lms#50]
Hi,

I'm wondering if it's possible to roll my LMS instance back to a prior version, since the plugins I use haven't been updated to work with v8.3.1?

**Comment by pssc** [comment]
> Hi,
> 
> I'm wondering if it's possible to roll my LMS instance back to a prior version, since the plugins I use haven't been updated to work with v8.3.1?

In  you can roll back to your backup, you may have to restore /config/lms back from a backup also.

What plugins are not working?

**Comment by Jizzay1** [comment]
I just upgraded to v8.3.1 and all looks OK except for my favorite plugin Chromecast Bridge won't start.  i don't even see the checkbox to "start" the plugin.  anyone else?

![image](https://github.com/pssc/ha-addon-lms/assets/87614052/f54f5ee6-c122-418a-9e57-251de662a170)

**Comment by jannislehmann** [comment]
Hey 👋🏻 ,
I've noticed the same issue with the recent update.
For me the AirPlay Bridge no longer starts due to a missing SSL library:
```
[07:40:36.067592] main:1533 Starting squeeze2raop version: v1.3.1 (Aug  9 2023 @ 21:21:14)
[07:40:36.070887] Start:1268 Cannot load SSL libraries
[07:40:36.071279] main:1597 Cannot start, exiting
```
I hope this helps!

**Comment by pssc** [comment]
I suspect this is related to the Debian base is now for bookworm change rather than 8.3.1 unless it's a known issue 8.3 has been out for a while...

**Comment by kylepyke** [comment]
> Hey 👋🏻 , I've noticed the same issue with the recent update. For me the AirPlay Bridge no longer starts due to a missing SSL library:
> 
> ```
> [07:40:36.067592] main:1533 Starting squeeze2raop version: v1.3.1 (Aug  9 2023 @ 21:21:14)
> [07:40:36.070887] Start:1268 Cannot load SSL libraries
> [07:40:36.071279] main:1597 Cannot start, exiting
> ```
> 
> I assume that an `openssl` library is missing, but looking at the recent changes, I'm surprised that it broke now. I might have some time to tinker with this later this week. But you might have more experience with that already. I hope this helps!

I reached out to the AirPlay Bridge developer because I had the same issue. It still works if you use the static binary, which is found in a drop-down under the Airplay Bridge plugin settings.

**Comment by pssc** [comment]
@kylepyke thanks for the work round anything else not working?

**Comment by Jizzay1** [comment]
> I just upgraded to v8.3.1 and all looks OK except for my favorite plugin Chromecast Bridge won't start. i don't even see the checkbox to "start" the plugin. anyone else?
> 
> ![image](https://user-images.githubusercontent.com/87614052/260904175-f54f5ee6-c122-418a-9e57-251de662a170.png)

Additional detail from the logs; appears to be SSL library related

[13:45:57.375013] main:1714 Starting squeeze2upnp version: v2.2.3 (Aug  4 2023 @ 21:27:36)
[13:45:57.376789] Start:1433 Cannot load SSL libraries
[13:45:57.376836] main:1751 Cannot start, exiting
[23-08-16 13:46:27.3563] Plugins::UPnPBridge::Squeeze2upnp::beat (177) load failed or crashed ... restarting

**Comment by pssc** [comment]
So looking at the Debian bookworm release only libssl3 is provided and i suspect the only one now in security support, so there is nothing easy I can do. The best option here is to use the static Binary from the Select Binary Option in the plugin.

**Comment by pssc** [comment]
Can someone try Adding libssl-dev as an additional package in the addon config and seeing if that works

**Comment by jannislehmann** [comment]
Thanks for quickly looking into this!
I managed to build the add-on locally with libssl-dev included and the issue was fixed while using the non-static version of the AirPlay Bridge.

**Comment by pssc** [comment]
> Thanks for quickly looking into this! I managed to build the add-on locally with libssl-dev included and the issue was fixed while using the non-static version of the AirPlay Bridge.

Thanks @jannislehmann that confirms my own findings, btw you should have just been able to add it to the packages config in the addon...

**Comment by pssc** [comment]
709a8549c0472cb8d6f418554a8722938abe33a5 includes libssl-dev by default upgrade to v8.3.1.56

**Comment by kylepyke** [comment]
Hmmm... Upgrading to v0.0.56 didn't work for me with Airplay Bridge. I'm still forced to use the static version of the plugin. Is there anything I need to do in addition to upgrading?

**Comment by pssc** [comment]
@kylepyke think there has been some confusion here between CastBridge and Airplaybridge...

**Comment by pssc** [comment]
Nope didn't quite make it with that version

**Comment by pssc** [comment]
Ok I can  confirm both now start, all the builds will finish in about three hours or so, I will release the new version when there done.
