### ISSUE TITLE
Missing local media Artwork

### ISSUE THREAD

**Issue by Flipsoo** [pssc/ha-addon-lms#63]
Hey there,

im missing the local media artwork. I setted up everything so if playing the artwork is shown, but in the folder view there is none and if i follow the link to the picture i get to an Error 404 Page.

Is this an known issue, if yes im sorry for double posting.

Bests,

**Comment by pssc** [comment]
Hi @Flipsoo,

So this should work and indeed does work on my systems so something else is going on is this via ingress and are use using a remote library? Can you give an example of an Image URL that fails?

**Comment by pssc** [comment]
@Flipsoo more information required

**Comment by Flipsoo** [comment]
im so sorry for this delay, but the latest update fixed it for me - thanks for your solving and again sorry for my missing reply
