### ISSUE TITLE
can't create new dynamic playlist or custom skip filter - erorr 404 not found

### ISSUE THREAD

**Issue by steamboy23** [pssc/ha-addon-lms#65]
installed on Home Assistant OS, not altering any settings of the addon. 
![image](https://github.com/pssc/ha-addon-lms/assets/18236954/8354be09-bfbb-4abb-a656-a993c0d72737)
everything works except Dynamic Playlist Creator and Custom Skip show error 404 - not found, when i try to create a new dynamic playlist or custom skip filter.
![image](https://github.com/pssc/ha-addon-lms/assets/18236954/1c8861b8-e122-43f9-a6a6-c6f4c4405d54)
![image](https://github.com/pssc/ha-addon-lms/assets/18236954/8f7bdf24-3de1-4036-b662-d1d5d9a16352)
i didn't find any error in the log files either.
also when i try to change the parent folder location of any plugin i get an invalid argument error. not sure if it's an issue or not.
![image](https://github.com/pssc/ha-addon-lms/assets/18236954/7709d369-772d-4949-b3ed-a5b333424d9c)
thanks for help.

**Comment by pssc** [comment]
@steamboy23 does the new version fix this for you?

**Comment by pssc** [comment]
@steamboy23 I can replicate your 404

**Comment by steamboy23** [comment]
> @steamboy23 I can replicate your 404

Hi, unfortunately the update did not fix the issue. However, if I access the server at localhost:9000, everything seems to be working fine. Thank you
