### ISSUE TITLE
Qobuz artwork not showing on material skin when started from within HA

### ISSUE THREAD

**Issue by jm38410** [pssc/ha-addon-lms#7]
Hi,

A weird bug:

When specifying skin : material and starting the lms from within HA, Qobuz artwork don't show up. Other artwork do show up in this configuration though (local music or radios)

But if I invoke directly the LMS UI from homeassistant:9000/material, Qobuz artworks  do show up. (maybe a DNS problem that appears only when launching the UI from HA?)

Thanks for your help
Jean-Michel

**Comment by pssc** [comment]
This should be fixed in the current relase
