### ISSUE TITLE
Server UI change issue in LMS HA addon

### ISSUE THREAD

**Issue by majo551** [pssc/ha-addon-lms#71]
I tried changing the UI setting of the server to a different mode. It turned to a simplified version , and since then I am not able to revert back to the full version. I tried to reinstall the  HA addon, but it keeps the simplified version:
![image](https://github.com/pssc/ha-addon-lms/assets/13347592/8bfe634e-8f25-4a34-8bb4-e38bd273d4ed)

 When I select any setting option in the dropdown menu, the screen becomes blank/black. I have to close and restart the UI  to get back to the basic screen again, which makes me impossible to make any change to the server setup. 
![image](https://github.com/pssc/ha-addon-lms/assets/13347592/cb50e1ca-fa06-4426-aade-93a4c05c8ad5)

![image](https://github.com/pssc/ha-addon-lms/assets/13347592/aad459f5-50ba-407b-88c8-18920602f106)

I use version  8.3.1.60 of the server
in
![image](https://github.com/pssc/ha-addon-lms/assets/13347592/e6479b8c-fa25-4443-81bb-b9457c468417)

Is there a way to reset the server to the original UI?

**Comment by pssc** [comment]
goto the native web interface on port 9000 try there first...

**Comment by majo551** [comment]
Thanks. I was able to get to the Interface page and change the setting to the default on port 9000, though the UI looked then even worse and I could not reach the setting option anymore (was at the bottom of the page reaching out of the screen scope :-)  So I  tried to reset all cookies and the page returned to default UI after reload.
I will not try rather other setting options in HA :-) This is buggy part of the UI
